FROM ghcr.io/astral-sh/uv:0.8.4 AS uv
FROM python:[[ python_version ]]-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

WORKDIR /app
COPY --from=uv /uv /uvx /bin/
COPY pyproject.toml ./
RUN uv sync --no-dev
COPY app ./app
[% if database == "postgresql" %]COPY alembic.ini ./
COPY alembic ./alembic
[% endif %]

EXPOSE 8000
CMD ["uv", "run", "--no-sync", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
